version: 0.2



phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 991492039835.dkr.ecr.us-east-1.amazonaws.com
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t node .
      - docker tag node:latest 991492039835.dkr.ecr.us-east-1.amazonaws.com/node:latest
     
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 991492039835.dkr.ecr.us-east-1.amazonaws.com/node:latest
      - echo Writing image definitions file...
      - printf '[{"name":"node-br","imageUri":"991492039835.dkr.ecr.us-east-1.amazonaws.com/node:latest"}]' 991492039835.dkr.ecr.us-east-1.amazonaws.com/node:latest > imagedefinitions.json

artifacts:
    files:
        - imagedefinitions.json